### ISSUE TITLE
@context value is resolved by html page insted to be JSON object

### ISSUE THREAD

**Issue by nemanjamil** [1EdTech/openbadges-specification#574] opened 2024-06-03 09:51 UTC
On the official documentation page https://www.imsglobal.org/sites/default/files/Badges/OBv2p0Final/index.html, the JSON object contains an @context key-value pair with the value https://w3id.org/openbadges/v2.

The issue is that this URL resolves to an HTML page instead of a JSON object.

Could you check for errors and see if the redirect needs to be fixed on your end to point to a JSON object instead?

![image](https://github.com/1EdTech/openbadges-specification/assets/13393375/16c869db-6832-44ca-ab7b-f95cae6ed3e0)

**Comment by xaviaracil** [comment] 2024-06-03 11:40
Hi @nemanjamil 

https://w3id.org/openbadges/v2 redirects to https://openbadgespec.org/v2/context.json, a site managed by the Mozilla Foundation. The issue is that any request to openbadgespec.org redirects to the spec document file.

We contacted the Mozilla Foundation – owners of openbadgespec.org – with the issue the same Friday May 31st. We're waiting for them to solve. Also, I've been trying to fix the redirection from its beginning, raising a pull request to w3id.org to redirect directly from https://w3id.org/openbadges/v2 to our server. You can follow this PR at https://github.com/perma-id/w3id.org/pull/4158

**Comment by xaviaracil** [comment] 2024-06-03 14:28
Since the PR has been successfully merged, https://w3id.org/openbadges/v2 now redirects to the right file.

**Closed by xaviaracil** 2024-06-03 14:28 UTC
