### ISSUE TITLE
Achievement `criteria` and `description` seem redundant

### ISSUE THREAD

**Issue by amiller-ims** [1EdTech/openbadges-specification#517] opened 2023-03-09 18:26 UTC
Achievement `criteria` and `description` are both required properties, but the distinction between them is ambiguous. `criteria` comes from OB 2.0. `description` comes from CLR 1.0. `criteria` was omitted from CLR 1.0 because CLR 1.0 added machine-readable criteria in the form of result descriptions. `description` in CLR 1.0 could be used to summarize - in a human readable format - how the achievement could be earned (which is also the purpose of the Criteria `narrative` property), and the Achievement `id` property can be used to point to a human readable web page that describes the criteria for the achievement (which is also the purpose of the Criteria `id` property).

I suggest removing the `criteria` property and Criteria class.

**Comment by kayaelle** [comment] 2023-03-10 21:33
Hey @amiller-ims - actually description came from the original OB spec. In the original spec, description was set to be 255 characters. So description was intended to be a short description and criteria a more elaborate one.

**Comment by ottonomy** [comment] 2023-03-23 16:02
👍 @kayaelle: short description vs specific instructions 

Additionally, criteria.narrative enables markdown and description is expected to be plain text. These fields have different purposes and are widely widely implemented as separate fields across dozens of products. In the course of implementing several badge products, I have not encountered users having confusion about the difference between these fields.

**Comment by xaviaracil** [comment] 2023-03-23 16:27
Workgroup agrred on not taking any action and close the issue.

**Closed** 2023-03-28 15:38 UTC
